language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    - secure: "bac0qFFpUhwleqJIvKXrQFMVcwlHACGy3K0ahEZ3pj+SHFl1S1BI6X6OlqRLy1hx/FRk2IthqGTEHRCmY8VmixYtN2Zeo2rtJALz3MC7FmLgchdTXaq3zpooMVh1HO9uDahm2QM4xXgc83rHyCJGQYgkEcv/P/7pUUXV3Eyl+uXyH+yLE02qU3ENQNuVyqeiJHBuw1heVFGDiCX8b2PiicXW1vuDOo3ShGXuz4fB/8qjhgqJeUr7obge7Xq0gnyWXrcjVD36P3QJhN/m7nyIogAv8gtnm8YPIQT1UVvQ+6cPoMg8CirXAcQVTZSpT0TvvoMaJts7TjUG19SbMPHWu4ckIFt/+UNks+B6Y1FIZl4CkULWqC7fBLHq9QUDNzRWGt/EaE5FF0qL3u/pu0HJtTCNv/Jw6cfpx+d9vmxQtpGEr5tzg6PjsCV+JL0yd2giyY7IoNHksNqjlwR9rf1irP1WMtWj+ir81gH2rd4XcsPvvrTbjrVXlI1CCDnRLWb3Z0L3WKQMwYszzkDX2XTJjdUhScyZynFtyeGsCFOd4YYSbELMISnWRwm4TkMsd0Ze3tKN442OaZujoq3Sn2McTK9tC6V9qzJayat1yJqNv7doMqbvqeVNZxAiMg600TcD++AUup0Jz0QB4piJ2AvNd3qjippyMQBIJHfD2mNBgFI="
