language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    - secure: "YlZjCKatX191risTXrngoOQqJoCmUYP3yxwiHd9j/MosHVW2ArCJpQGBl/EGmaFMIfv/aMywFUiamlt5OJU3FYC3Nx3v4MOr1K3Hha+NKpbfUeVtXLephPiZIV+gK80DqEC9RZ3VxqOTv0B44w59qoI+kzO8GvjcxKBZwjndrr+jnvuZIkpboE84EfoZ4p4PW1zfQn1oT3TIGT19jlPI2QNO8NBKyF+5ZzK+LgQ7d/UKdk7GN9R5ssHlaBX9Iwdl2qeC5SEhqH3DbL2nJp6BCfM1oHpv/ZqqzjVFfYBFomx5yVLKgfUSKi3h3Fi5Zl5TCh8u1T/udydnvla3xxMoCmNlBsbaOqAkiImYpDCihisaZ4aPPPrzVWm7xSRj3qhTVimfm0rxRdI6UXSzBC4OldZ06JDvdRVHgwKmZlu9VLsZx+kp7BI73axdhQjMNPQ+iRkyog3mLn4FgmJESo1s7sg1p7KRaCqsKrR/Psrv3YrfRKcpckNH9Mj3VhNMTEsMBbjKAWlnxQl49AUtbQ79e+aqh42gTX9HGQL109M/W8fcpPgwCIdvGrR23JFgSBgk3Gk2SGZYU607EZR/Bl+hdlND5tnmSDa+jNTMLhGpl41DIoLm9WTrU1+1k71W6zYUDczX/6LCiyUZLhPom7JzSia8VsKQm6ixtHAv7wa8hhY="
