language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    - secure: "lm/1Fc2qamYXmdRLZJ+CeL75w1Owrd3k5kNbU1P73SQnhRAfjBhTc/fqk1Dptfms5BQbHmCZ89zRTs1trWWkeLlJ5u5Zq/fYIhCJ33+l6WOYMvPgOzZ/z0XKTgU3d9LGoQlSYzSN8un1XlOl6KkJODyhYMy47oZzmyyHdH+zWnLgczMilLl5v3SJn8z8Cv0rW3jb/ScxnjT3FyoMhfeBX3Xkn/ZN1bhSaGy/xkuh8krqsMVdla+0xGeX5i1e5bzJnJIc5g40pOzNxLL/QbPsr8e+vngVYzga3i71nM5B3Er0v2WRXytMgmN8s9AJ0c/OjgOQwftkdZMlWF30TMjjEolMVRTBe9U9Yj4lLnvJ6UGLB4i08x8SjVwngefYsOp3jYABBkWPmQcmBH5tjeQm52V4E6/GMTW4Xh9jcWN+PLILlmjJ2PQZ16fYkptYWo9/a4b17kZlzalrt9gDPj1vKO+jKSIOCuM9rEIOq4JPHXVoXwcjKSokrXcSBL47knGPTtsx7y/VHbuGx5My/FfH965ZuvvQ8LgxzMyukQHrQNpWHwS7uMlj3eZhpVXDsitWMdgf6CB3hSkAYN7cxIQOKkufHT6H8czG+8gp2DnaZZsqRDBykCoo8PE2A/ADbAQy9PKg9AbKTWeBR6Rr8GEBsfYeHT+BsU1mWjoVquYH4T0="
