language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    - secure: "r/yWVZWT9zmp4GnWb8BWYEuREi/+lHx+PDQwmrI7zey/MfnOIqKKlbzmnbFuFwrZ8FLEi6j0OMzGK0GV0KbLn/4S1iZXeU7W+i7eU86aifNI120tHLjvftNVsCwLN/04FwZbTWPpJ64iUbzqVy9fEiy3fNCzu8LIxFP0yqYHvAs0aQWyRYvMJ0Q2b94Zcftc3gTBdDQs3f+67FImzgoWoJrQh3o3DmjiQ4vjbmD3F9/OyoC0m+sj5f65ItdEL2K7/8hXZ13rTEhdzbPtZWeoASjFZ/498EQYBWVtwYGrlWm5fA1uiM493sThuzzf62sapezn8akA5X6jyPLBrrO5Jnr/td9Lgi6uF/lQLgcauaVx0ly0vxw4ZgQH95XNHYzFgmgrghGqhWsR9Q/cCsKBoCEINocYmP1DPrHIMOe3o6pCb+fIUZT0VYVZH3Ywgx/0Qxkrr/lJ0/KuKDAay581zJ0O64t16aep3b1DeyuEzhkDAdVYKyYBpt8S3eqwshRMTyhm8yapxMinSuACBL9Vf0n++8TqDz6XnEVzSC4jVWR5nRYCrz1FSo3z82rfenNYVK3I9KDTGIkVs4bLlQXtw1KRrj/tEDlsaV/oug0CRFazcS3jgUpKWA5+t6YPTudlhcP6TiS5LmwiLp/mg1oqbqVkuiG9MX9re4aCKTRqbTI="
