language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    secure: "qdIHv++tS4y1U9r+PIz2LvZopjM9ZmPsBI8WoL35yGGeG0mLkltdMMY9F2FNJajLZKM14MIvjflXP2BBwAwjip8FhWjsIdTNfvSxREKJ++1wtGvImZpN+gNSXzEpn3QAEP4bYoBctHsMsLFvj6aznK9HwxZpfAln94gQ5fwUL76/f0Bm/zZVa67IxGTj4nl4SkWaX5118SFW59ndY04GrQ2tLoByacdnXL36VTSLfl9ONhGJMHVnItMpTulzV/yyDXQp7CvsAfJmUaWmVBAUGACQcKuTX9Xw+UsPcTTuHtQWdomweeC5LzDcW80tdop4D3TSaypxoJhzufeAvG7nf1ueMltTkMPUjRuveOggJTJKNHCrqOpYephp3wkgox24LliygXiMIHtMM336fs64BsZGvksKVE4UarOjgsnA/7EOHwQtPqzTqVXdVJ2EMzWknyGE07M+5TaAUSBk/E1Fgo1SXHlQkqQRU64Q2Lp+yLpMOYPLLV6+r/3rzoqWbO5Dw0S3/rUUMgakuJDSmvIDNj4ouEeP2j3EgnbfYduCLtQ+HwLA8y26HLVASH5jp8rzbVW32jJYhmz9tVgYwcVm9dGE4rmFEjHSv1RT1P8rn92/ikkKStW8yICNottl7zb1AEH37XTM2LxukFSDCDoQ5N87vPfd06b5KTyCqaQbkjI="
