language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    - secure: "WdKw/mbTaf6lmGvKK/Dwk3in2haXiY30B4yb572T0akD53W2xQKuAMK00y2RWSqu31SHpfLJcV/GwPV/XdBojS8arz0YzVn9z/kL9UP5AKjOIwjkoW/48RlQdVV4P5TO2sBccmYtmhkORzkx0IoCI6R+iFwlPCqcduwbj4O2FBxPX+FUfaEmzIrRdsId23Byae6haaG8iKVVgJwwM6WINTI4r4pojAO4Gey7xGkHjBy1YgTpFZBwUU4MlqqKmm70QPCFuUCfpmqwNYKlT6P8rNaCKbU1KfkgClI2Xhp+8X5/dV0Xi6RUChQmaZ++TBLELiuKJkTjcy+/gBPV/fsP5eDAx4QALwSZr6wExfQM2lQnkzAc6Bv2un8IvMOotWPrxo7AZOSpyStio/YFDqY0ZaWbiCVdQUvpK262+LE+2CK9nMHVL6Nqgl6SSMQt3xuIsKOkZcn/QY6M//kEVv2ZBCxj28BaHnnZMJCjpcAfAPrzkZPUQjxZLFfORvaaKw+2hr0sjDPsxfPVvqa+Low1/FazAvzjOmRzqioLVfZZhiCKO+TiInxOLKl1f7VlyAYyew7f8QQuuNRQKOmUUmGct7XpnKhQdWB5HFvkjVK0zqgmPrKwN03F+gUJKAF6Sy71sjlhRvIdYhY61Ta7lUxJoswUK43OTo0MGLV4TVBAuhQ="
