language: ruby
rvm:
- 2.5.3
branches:
  only:
    - main
install: bundle install
cache:
  directories: vendor/bundle
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec ruby deploy/deploy.rb; fi'
env:
  global:
    - secure: "h8wOQ4mzDt3wtuQ4YRXJk/TDcxBWFYThA0aX9MKsjWhpLvrzZqdts4KJqCe6xvflM9f7LrhxgLg9802JSUz9rP3mQCxPJJuKYFL1XcWw46AtTlbJP/ilXs7gcAzUHWEwIvRHz6efJos/Fkpl9W5lDPx4PGUJ54Da4+qnLMovE7nrcaVHkZGuZ/dS4A/1S7jZXsPwiYVpfg15gaFFGTWfOi1bHJ0x1bSLuPvvwn6izBbaz4maDAPh2EUAlJEUim/zu52SlgTHgEhsbzGW+kuDPtszmL6T9AjmBgC57/OkeyvTGKdDNu8SFtqbsOuz51phRmPSKoLlfwwMszUTxk2mG1znWC2yQGogU3323w8Z47gaY//k57sda1bfZT++emElLgZ8oABZ88tQQh5Pset1iD6mIcBpnfRj396JqswWBGeDU1WSiTdpqRDG4eUV4ukzKdOhIXeBp+ceJsNN/uZXadnLDOGR0LR0eqt1IjYs5YJ3QYjIjziP1xnRZRHvX/hTELbmPowyg9E9iQoH3R2ONvpi6omkdpgkTQdcJnZ5oREGXmRrEw3DoHqTaLvaU7qDHsmgPB5XypEbKTFFU/OUTNeYjcF14kDvB2zlseKFnf7AUa7AP4NkrWAaE1ZTfN3UGme/50jUjIuhlKK8P3GZOhdYG13NASvYYCrzJFy8Jpo="
